name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend-sonarcloud:
    runs-on: ubuntu-latest
    name: Analyze Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Compile the project
        run: mvn compile

      - name: Run unit tests
        run: mvn test

      - name: Run tests and generate Jacoco report
        run: mvn verify jacoco:report

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-backend-${{ hashFiles('**/backend/**') }}
          restore-keys: |
            ${{ runner.os }}-sonar-backend-

      - name: Run SonarCloud analysis for Backend
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=triny81_bobapp-backend
            -Dsonar.organization=triny81
            -Dsonar.sources=back/src
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=back/target/classes
            -Dsonar.junit.reportPaths=target/test-classes
            -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

  frontend-sonarcloud:
    runs-on: ubuntu-latest
    name: Analyze Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch full Git history
        run: git fetch --unshallow

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Run tests with Karma
        run: |
          cd front
          npm run test -- --code-coverage --browsers=ChromeHeadless --watch=false

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-frontend-${{ hashFiles('**/frontend/**') }}
          restore-keys: |
            ${{ runner.os }}-sonar-frontend-

      - name: Run SonarCloud analysis for Frontend
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./front
          args: >
            -Dsonar.projectKey=triny81_bobapp-frontend
            -Dsonar.organization=triny81
            -Dsonar.sources=src
            -Dsonar.exclusions=node_modules/**,coverage/**,dist/**
            -Dsonar.tests=src
            -Dsonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
            -Dsonar.qualitygate.wait=true

      


      

    
      

